Add test for key file
Signed-off-by: Benoit Donneaux <benoit@leastauthority.com>

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -15,7 +15,7 @@ on:
       - 'action.yml'
 jobs:
   test_defaults:
-    name: Test defaults
+    name: Test defaults with key string
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -40,6 +40,51 @@ jobs:
         uses: ./
         with:
           private_key: "${{ steps.prepare.outputs.private_key }}"
+
+      - name: Verify
+        id: verify
+        run: |
+          test $(ssh -a -x -o StrictHostKeyChecking=no $(whoami)@localhost whoami) = "$(whoami)"
+
+      - name: Proper exit
+        run: |
+          if [ ${{ steps.prepare.outcome }} != 'success'\
+                -o ${{ steps.call.outcome }} != 'success' \
+                -o ${{ steps.verify.outcome }} != 'success' ]
+          then
+            echo ":x: Test failed" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          else
+            echo ":heavy_check_mark: Test succeeded" >> $GITHUB_STEP_SUMMARY
+          fi
+        if: success() || failure()
+
+  test_defaults:
+    name: Test defaults with key file
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Prepare key pairs
+        id: prepare
+        run: |
+          # Generate key pair
+          ssh-keygen -t ed25519 -f ./test_key -P ''
+          echo "private_key<<EOF" >> $GITHUB_OUTPUT
+          cat ./test_key >> $GITHUB_OUTPUT
+          echo EOF >> $GITHUB_OUTPUT
+
+          # Authorizing pub key
+          mkdir ~/.ssh && chmod 0700 ~/.ssh
+          cat ./test_key.pub >> ~/.ssh/authorized_keys
+          chmod 0600 ~/.ssh/authorized_keys
+          sudo systemctl status sshd || sudo systemctl start sshd
+
+      - name: Call action with key string
+        id: call
+        uses: ./
+        with:
+          private_key: "./test_key"
 
       - name: Verify
         id: verify
