Support path to key as input (#6)
* Support path to key as input
* Add test for key file
* Update documentation accordingly
* Fail if the key file is not on tmpfs
* Add test to verify key file is in tmps

---------

Signed-off-by: Benoit Donneaux <benoit@leastauthority.com>

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -14,8 +14,8 @@ on:
       - '.github/workflows/integrate.yml'
       - 'action.yml'
 jobs:
-  test_defaults:
-    name: Test defaults
+  test_defaults_string:
+    name: Test defaults with key string
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -35,22 +35,20 @@ jobs:
           chmod 0600 ~/.ssh/authorized_keys
           sudo systemctl status sshd || sudo systemctl start sshd
 
-      - name: Call action w/o inputs
+      - name: Call action with key string
         id: call
         uses: ./
         with:
           private_key: "${{ steps.prepare.outputs.private_key }}"
-        continue-on-error: true
 
       - name: Verify
         id: verify
         run: |
           test $(ssh -a -x -o StrictHostKeyChecking=no $(whoami)@localhost whoami) = "$(whoami)"
-        continue-on-error: true
 
       - name: Proper exit
         run: |
-          if [ ${{ steps.prepare.outcome }} != 'success'\
+          if [ ${{ steps.prepare.outcome }} != 'success' \
                 -o ${{ steps.call.outcome }} != 'success' \
                 -o ${{ steps.verify.outcome }} != 'success' ]
           then
@@ -59,3 +57,94 @@ jobs:
           else
             echo ":heavy_check_mark: Test succeeded" >> $GITHUB_STEP_SUMMARY
           fi
+        if: success() || failure()
+
+  test_defaults_file:
+    name: Test defaults with key file
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Create tmpfs to write the key
+        id: tmpfs
+        uses: LeastAuthority/mount-tmpfs-action@v1
+
+      - name: Prepare key pairs
+        id: prepare
+        run: |
+          # Generate key pair
+          ssh-keygen -t ed25519 -f "${{ steps.tmpfs.outputs.mnt }}/test_key" -P ''
+          # Authorizing pub key
+          mkdir ~/.ssh && chmod 0700 ~/.ssh
+          cat "${{ steps.tmpfs.outputs.mnt }}/test_key.pub" >> ~/.ssh/authorized_keys
+          chmod 0600 ~/.ssh/authorized_keys
+          sudo systemctl status sshd || sudo systemctl start sshd
+
+      - name: Call action with key file
+        id: call
+        uses: ./
+        with:
+          private_key: "${{ steps.tmpfs.outputs.mnt }}/test_key"
+
+      - name: Cleanup
+        id: cleanup
+        shell: bash
+        run: |
+          sudo umount "${{ steps.tmpfs.outputs.mnt }}"
+        if: steps.tmpfs.outcome == 'success'
+
+      - name: Verify
+        id: verify
+        run: |
+          test $(ssh -a -x -o StrictHostKeyChecking=no $(whoami)@localhost whoami) = "$(whoami)"
+
+      - name: Proper exit
+        run: |
+          if [ ${{ steps.tmpfs.outcome }} != 'success' \
+                -o ${{ steps.prepare.outcome }} != 'success' \
+                -o ${{ steps.call.outcome }} != 'success' \
+                -o ${{ steps.verify.outcome }} != 'success' ]
+          then
+            echo ":x: Test failed" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          else
+            echo ":heavy_check_mark: Test succeeded" >> $GITHUB_STEP_SUMMARY
+          fi
+        if: success() || failure()
+
+  test_defaults_file_unsafe:
+    name: Test defaults with unsafe key file
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Prepare key pairs
+        id: prepare
+        run: |
+          # Generate key pair
+          ssh-keygen -t ed25519 -f ./test_key -P ''
+
+          # Authorizing pub key
+          mkdir ~/.ssh && chmod 0700 ~/.ssh
+          cat ./test_key.pub >> ~/.ssh/authorized_keys
+          chmod 0600 ~/.ssh/authorized_keys
+          sudo systemctl status sshd || sudo systemctl start sshd
+
+      - name: Call action with unsafe key file
+        id: call
+        uses: ./
+        with:
+          private_key: "./test_key"
+        continue-on-error: true
+
+      - name: Proper exit
+        run: |
+          if [ ${{ steps.prepare.outcome }} != 'success' \
+                -o ${{ steps.call.outcome }} != 'failure' ]
+          then
+            echo ":x: Test failed" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          else
+            echo ":heavy_check_mark: Test succeeded" >> $GITHUB_STEP_SUMMARY
+          fi
+        if: success() || failure()
diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -22,22 +22,48 @@ runs:
     - name: Create tmpfs to write the key
       id: tmpfs
       uses: LeastAuthority/mount-tmpfs-action@v1
+      if: startsWith(inputs.private_key, '-----BEGIN OPENSSH PRIVATE KEY-----')
 
-    - name: Start an agent with the key from tmpfs
-      id: agent
+    - name: Write the key to tmpfs
+      id: key_to_file
       shell: bash
       run: |
-        echo ":rocket: SSH agent operations started" >> $GITHUB_STEP_SUMMARY
         # Import secret key in memory
         cat <<EOF > "${{ steps.tmpfs.outputs.mnt }}/ssh_key"
         ${{ inputs.private_key }}
         EOF
         chmod 0600 "${{ steps.tmpfs.outputs.mnt }}/ssh_key"
+      if: steps.tmpfs.outcome == 'success'
+
+    - name: Verify key file
+      id: verify
+      shell: bash
+      run: |
+        # Define path to key
+        if [ ${{ steps.tmpfs.outcome }} == 'success' ]; then
+          path_to_key="${{ steps.tmpfs.outputs.mnt }}/ssh_key"
+        else
+          path_to_key="${{ inputs.private_key }}"
+        fi
+        # Fail if key file in not on tmpfs!
+        df "${path_to_key}" | tail -1 | grep -q "^tmpfs" || {
+          echo ":x: File private_key is not on tmpfs: consider revoking!" >> $GITHUB_STEP_SUMMARY;
+          exit 1
+        }
+        # Store key path for next step
+        echo "PRIVATE_KEY=\"${path_to_key}\"" >> $GITHUB_ENV
+
+    - name: Start an agent with the key
+      id: agent
+      shell: bash
+      run: |
         # Load key with agent
+        echo ":rocket: SSH agent operations started" >> $GITHUB_STEP_SUMMARY
         eval "$(ssh-agent -a ${{ inputs.auth_sock_path }} -s)" \
         && echo ":heavy_check_mark: SSH agent creation succeeded" >> $GITHUB_STEP_SUMMARY \
         || { echo ":x: SSH agent creation failed" >> $GITHUB_STEP_SUMMARY; exit 1; }
-        ssh-add "${{ steps.tmpfs.outputs.mnt }}/ssh_key" \
+        # Load the key in the agent
+        ssh-add "${{ env.PRIVATE_KEY }}" \
         && echo ":heavy_check_mark: SSH key loading succeeded" >> $GITHUB_STEP_SUMMARY \
         || { echo ":x: SSH key loading failed" >> $GITHUB_STEP_SUMMARY; exit 1; }
         echo "pulbic_key=$(ssh-add -L)" >> $GITHUB_OUTPUT
@@ -49,3 +75,4 @@ runs:
       shell: bash
       run: |
         sudo umount "${{ steps.tmpfs.outputs.mnt }}"
+      if: steps.tmpfs.outcome == 'success'
